@"
# This file generates the GitHub Actions matrix
# For simple board+shield combinations, add them
# in this top level
include:
  - board: nice_nano
    shield: 17pad
"@ | Out-File -FilePath E:\github\zmk-config\build.yaml -Encoding utf8