manifest:
  remotes:
    - name: micahyy
      url-base: https://github.com/micahyy
  projects:
    - name: zmk
      remote: micahyy
      revision: d55c55a9a9a60c0e274088ffb3017195a885e625
      import: app/west.yml
  self:
    path: config
