manifest:
  remotes:
    - name: micahyy
      url-base: https://github.com/micahyy
  projects:
    - name: zmk
      remote: micahyy
      revision: 6634e6a344372e2bae0e23609cb79b80ec0f3d23
      import: app/west.yml
  self:
    path: config
