manifest:
  remotes:
    - name: micahyy
      url-base: https://github.com/micahyy
  projects:
    - name: zmk
      remote: micahyy
      revision: d02621f8df5194cf81e39132bd195e8bf73f32e8
      import: app/west.yml
  self:
    path: config
